import Header from "@/components/Header";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import NowPlaying from "@/components/NowPlaying";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className="bg-[#1e1e1e] text-white">
        <Header />
        <div className="flex">
          <Sidebar />
          {children}
        </div>
        <NowPlaying />
      </body>
    </html>
  );
}
